### PR TITLE
Re-adding added value PD

### PR DESCRIPTION
**Pull request by cshenry**

### CODE REVIEW

**Comment by aparkin** [comment]
Do you have to budget time to ensure search and landing pages update with these value added plugins.

**Comment by cshenry** [comment]
So sprint 4 includes the landing page updates, but yes, the search would need some update as well... although not alot... except of course, adding capacity for biochemistry search.

And of course, as usual, my schedule contains nothing about docs and testing... those will need to be added if we select this one.

**Comment by aparkin** [comment]
Add 'em now! Make a statement!

**Comment by cshenry** [comment]
Did you not see how many commits and attempts it took me to get the PRs to show up properly on github?? :)

I need to figure out how to edit a PR...

**Pull request merged**
