### PR TITLE
Update RNA-seq service update.md

### PR DESCRIPTION
**Pull request by vkcshl**
Updated the text as user stories.

### CODE REVIEW

**Comment by aparkin** [comment]
I am a little worried that this is mix of a set of  "requirements", wish list, and product description. 
1) The concrete deliverable functionality should be explicit where possible. For example: "User can see the functional information and GO annotations on the list of differentially expressed genes in Expression matrix and HeatMap." This is a bit confusing to me. Is the idea that the user will be able to select a set of clusters somehow and ask for an enrichment analysis of GO terms? How will selection work? What method of enrichment analysis will be implemented? How will it be visualized? 
2) How much of your work cannot be done without the requirements or wishes you have below? Given the current work and the new PDs -- are you covered -- and are you covered in time to perform on this during this quarter? You might want to break up the PD into things you can do right now, things you can do once bulk upload is possible, etc.
3) I would like to see a serious PD on collecting information on how users want to and do interact with the current system and have that drive design of the next generation.

**Comment by vkcshl** [comment]
My understanding was that product description should include requirements and relevant wish-list. We have captured the design and planning details in [another document](https://docs.google.com/document/d/1QzFDjWPKem1hFxHiDJOOjnnYc0c-LBN3ZIixm5RvJJU/edit#).

1) The scope of this PD is to simply show the functional annotation for the genes in the FeatureClusters output table generated by the underlying clustering algorithm. This information will be pulled in from the GenomeAnnotation object. However, once the gene set enrichment is available in KBase in near future, then these clusters can be enriched based on any number of techniques discussed in the [enrichment PD](https://github.com/kbase/roadmap/blob/master/Proposed%20product%20descriptions/Ontology%20Search%20and%20Enrichment%20Services%20in%20KBase.md) and associated PR.

2) Addressed in the [planning/design document](https://docs.google.com/document/d/1QzFDjWPKem1hFxHiDJOOjnnYc0c-LBN3ZIixm5RvJJU/edit#) and the [new RNA-seq tools PD](https://docs.google.com/document/d/1hKjGw3bLz6wvJJ0MMbVX2BYZ5kolhO8m4F8bqcKZYYg/edit) draft. The draft PD draft will be uploaded to GitHub after the Euks team has a chance to review and discuss it further.

3) Not sure, if I understood the request - approach of collecting information vs. the information collected. 

If it’s former, we have and will continue to collect information during interactions with users in all kinds of venues and meetings, informal and formal. And that will inform the decision of the final set of tools shortlisted for porting to KBase. In the meantime, we are drafting a new PD for the list of next generation of ‘candidate’ tools related to RNA-seq analysis that will be used for short-listing. 

If it’s the later, here is some of the information we have collected based on the past interactions with SAC members and with users at meetings such as PAG, DOE, JGI, Biology of Genomes meetings. Mainly, faster and highly scalable robust RNA-seq pipeline with more and better visualization tools is what users would like to see in KBase RNA-seq pipeline for their publications. These have been discussed in our PDs and planning/design documents.
- Bulk uploader requirement to import reads
- Upload of new genome (assembly and annotations), if not in GenBank format.
- Reads QC and visualization (Assess fastq files using FastQC)
- Trimmomatic if reads need trimming
- Parallel execution of alignments for multiple samples in a single method (rather running separate same method for multiple samples) [Note: all alignment tools take one sample at one time to get the alignment to reference genome/reference transcriptome].
- Better visualization tool for BAM files
- Parallel execution of assembly for multiple samples in a single method (rather running separate same method for multiple samples) [Note: all assembly tools take one sample at one time to get the assembly].
- New tools for alignment, assembly and differential expression analysis (e.g STAR/HISAT2, Stringtie, Ballgown, DESEQ2 etc.)
- Better visualization tools for differential expression analysis results
- Functional analysis of the differential expressed results (e.g GO enrichment etc.)

**Comment by aparkin** [comment]
@vkcshl The PD should be a fairly precise definition of the deliverables for the project. A wishlist doesn't really address that need though it is an ok thing to include after the other bases are covered. If your product is not possible without other things being completed first-- and these things are not on schedule to be delivered in time for your proposed timeline then your product should not be proposed for this quarter. 

I am asking that the product-- due last wednesday-- be complete and clear on what it proposes to deliver and when. Your PD did not reference these other documents or I missed it.. but ideally it should not reference other documents that are about the product itself. I will read those documents but ideally the dependencies would be recorded here for others to see and comment. Again I ask.. is this product possible or are you too dependent on other things not planned to deliver before this quarter?

For 3 the point is to have a direct discussion of what and how users want to use the precise product proposed in this PD- maybe referencing the rest of the ecology of products briefly- but really focused on what users get from THIS product and how they want to use it. Ideally, you would design the functionality down to the way it operates in Narrative and get feedback from users on the paper outline; build the first version and let users try and use it; then refine based on your findings.

**Comment by vkcshl** [comment]
On May 15, 2016, at 12:50 AM, Adam Arkin <notifications@github.com<mailto:notifications@github.com>> wrote:


@vkcshl<https://github.com/vkcshl> The PD should be a fairly precise definition of the deliverables for the project. A wishlist doesn't really address that need though it is an ok thing to include after the other bases are covered. If your product is not possible without other things being completed first-- and these things are not on schedule to be delivered in time for your proposed timeline then your product should not be proposed for this quarter.

I am asking that the product-- due last wednesday-- be complete and clear on what it proposes to deliver and when. Your PD did not reference these other documents or I missed it.. but ideally it should not reference other documents that are about the product itself. I will read those documents but ideally the dependencies would be recorded here for others to see and comment. Again I ask.. is this product possible or are you too dependent on other things not planned to deliver before this quarter?

For 3 the point is to have a direct discussion of what and how users want to use the precise product proposed in this PD- maybe referencing the rest of the ecology of products briefly- but really focused on what users get from THIS product and how they want to use it. Ideally, you would design the functionality down to the way it operates in Narrative and get feedback from users on the paper outline; build the first version and let users try and use it; then refine based on your findings.

�

**Comment by r2sunita** [comment]
Currently, we are using Tuxedo suite for RNA-seq pipeline. There is no doubt that Tuxedo suite is a widely used pipeline for transcript assembly, quantification and flexible differential expression analysis at transcript resolution. This workflow has been used in many projects including the ENCODE and modENCODE consortium projects. However, recently, the emergence of new tools STAR, HiSat, StringTie, Ballgown, DESeq etc. will make RNA-seq pipeline faster and much more efficient. 

I think before we plan for Q3 PD on new tools in details, we need an intermediate PD that can address the planning and design for the new RNA-seq tools. We need to collect information from literature, clear benchmarking and reasons to support these tools, what can be doable in KBase (risks and dependency associated with tools), assessment and prioritization of these tools and feedback from expert in this domain where needed.

**Comment by r2sunita** [comment]
@aparkin @vkcshl Here is an example that shows why do we need to spend more time in the assessment, prioritization and design of tools in KBase narrative as an individual PD itself. 

Within warelab, we did benchmarking of some of new generation tools on alignments (Cuffdiff, STAR, HiSAT) and we found STAR is the winner on the greatest number of correctly assigned reads and speed.  This information is also consistent with other benchmarks reported in literature.  However, it is also reported in the literature that HISAT will  be very useful when memory is issue. HISAT scores great speed with a low memory footprint and also provides greater accuracy for alignment of reads containing SNPs and provide better options for transcript assemblers (e.g., StringTie and Cufflinks) to work better with the alignment from HISAT2. So before we select STAR or HiSAT/HiSAT2, we have to assess these tools based on our requirements, KBase environment, suitable on working in pipeline with already existing tools and new proposed tools.  Similarly, there are many pros and cons of other assembler and differential expression tools e.g DESeq or Ballgown. In addition, there are some tools related to Kmer expression estimation approaches such as Sailfish, Kallisto suite etc. which are superfast but do not believe in aligning the reads pr parts of reads to reference genome or transcriptome (these tools do pseudoalignments and therefore much faster than traditional tools which do believe in alignment paradigm). 

Moreover, the discussion on its assessment and prioritization will also help for us to discover underneath issues with these tools before we implement it in KBase. It will also help in better design of the methods for PD on new tools and in setting up more realistic expectations for users.

**Comment by vkcshl** [comment]
@r2sunita Since your comments refer to next generation of RNA-seq tools, let's have this discussion going forward in the context of Q3 PD. The PR is here: https://github.com/kbase/roadmap/pull/80

I agree, we need to allocate some time to narrow down and possibly revise the final set of tools enlisted in Q3 PD,  towards the tail end of Q2 while interacting with users and/or beginning of Q3 during initial planning. The time spent during this effort is really part of planning and implementation stage and will lead to revision of the Q3 PD linked in this comment. I am not sure if we need an intermediate PD for that but we need some definite chunk of time to work on it.

**Comment by r2sunita** [comment]
@vkcshl 

I do not have push access to make changes in the document on the Q3 PD  https://github.com/kbase/roadmap/pull/80

**Pull request merged**
