### PR TITLE
PD for Workspace GC

### PR DESCRIPTION
**Pull request by MrCreosote**

### CODE REVIEW

**Comment by aparkin** [comment]
Hi Gavin, 

So does referenceless mean there is no narrative or other data object that points to it? Does it apply to data that is part of a revision history: so for example in a version chain like data_very_old<---data_old<---data ... can one of these versions be deleted? Or is this provenance chain a reference?

Also you say: 
If data contains references to Shock data (via a Handle stored in the Handle Service), that Shock data will not be deleted because the data does not belong to the WSS.

Isn't this a problem? Won't we ultimately start accruing a bunch of mystery data in SHOCK?
Shouldn't we fix this issue?

**Comment by MrCreosote** [comment]
> So does referenceless mean there is no narrative or other data object that points to it?

Yes, it has no incoming dependency or provenance references as defined [here](http://ci.kbase.us/services/ws/docs/fundamentals.html#references).

> Does it apply to data that is part of a revision history: so for example in a version chain like data_very_old<---data_old<---data ... can one of these versions be deleted? Or is this provenance chain a reference?

Funnily enough, all the reference counts in the workspace are currently on a per version level, so we _could_ delete specific versions of data. That being said, I now think that's incredibly user unfriendly and it should be an all or nothing deletion of the object wilth all versions. Part of the schema change is to collapse the per version reference counts to a per object reference count.

> Isn't [not deleteting shock data] a problem? 

Yes.

> Won't we ultimately start accruing a bunch of mystery data in SHOCK?

I assume we already are.

> Shouldn't we fix this issue?

Yes, but I think it's beyond the scope of this PD.

**Comment by aparkin** [comment]
I suppose my point about SHOCK is that perhaps there SHOULD be a PD to deal
with sooner rather than later.

**Comment by MrCreosote** [comment]
OK, added to my TODO list

**Comment by mlhenderson** [comment]
If we use reference counts to track if a shock node is connected to an
object, once the count reaches zero we could schedule the node for deletion
on the next sweep.  We were discussing this for Blob API as well, however
since multiple versions of an object reference the same shock node, and
every copy also references the same shock node, it becomes difficult to
reach scenarios where the reference count reaches zero.

Additionally, we have data in shock that was never connected to a KBase
object.  Determining which data that is would not be impossible, but
certainly time consuming.  Part of the reason for that is because user file
uploads go directly to the production shock instance.  We never set up a
temporary shock instance for staging the data.  Doing that would virtually
eliminate new disconnected shock data, but we should also be able to
indicate that a shock node is not connected to a KBase object.  Having that
information stored in the node metadata would make it simpler to schedule a
cron job sweep for nodes that are orphans, and then delete them.  I don't
think this needs to be a workspace responsibility.

Is there a current estimate for the amount of workspace data that would
meet the requirements for GC?  Number of objects and total size in GB, and
what percentage that represents for total number of objects and total GB of
data.  How many users have data scheduled for deletion?  I know this item
has been on the backburner for a while for you, but it would help to
understand if there is a serious urgency to do it right now because this
will take resources from other efforts.

It seems like we do have an issue here that data is actually quite
difficult to delete currently unless it is never copied or never referenced
and then scheduled for deletion by the user.  If we do at some point decide
we need to issue user data quotas, this problem is going to become very
prominent.  I don't want to go way off into a tangent other than to say
that I think there are some serious system issues here that should be
further discussed.

**Comment by MrCreosote** [comment]
@mlhenderson 

> If we use reference counts to track if a shock node is connected to an object, once the count reaches zero we could schedule the node for deletion on the next sweep.

It's actually simpler than that - since handle IDs are 1:1 with shock IDs, just delete the node if there are no more workspace objects with the same handle when you delete an object.
However, there's still the major issue that the workspace actually has no authorization to delete the node, and has no idea if the owner of the node wants that node deleted.

> Is there a current estimate for the amount of workspace data that would meet the requirements for GC? 

No, and to be frank I submitted this assuming that it's not going to happen this quarter because currently it's causing us no pain (AFAIK anyway - @kkellerlbl, @danielolson5 any input?). My motivation for submission of both this and the WS/TD split are to make sure everyone is aware of the limitations of the WS and that at some point they need to be addressed. In other words, this PD at least needs to land in the backlog.

If there is a high likelihood that GC may be resourced assuming there's gigs and gigs of data to be freed, I'll go do the legwork to find out.

**Comment by mlhenderson** [comment]
Except we don't actually enforce handle references only in all types, some types still use shock references and not handle references, and certainly there is legacy data that does not use handles.  We would need some way of cleaning 'old' data if marked for deletion, assuming that data was isolated.

**Comment by MrCreosote** [comment]
Well yeah, if a object contains a shock node ID that the workspace knows nothing about (which is the case if it's not a @handle) then all bets are off, at least as far as any kind of deletion handled by the WSS is concerned.

**Comment by danielolson5** [comment]
This would be helpful, but we could likely go another quarter or two without cleanup. 

Let's try to fit this in after all of the high priority items are scheduled.  

Dan

**Comment by kkellerlbl** [comment]
I'm pretty sure that all the initial uploads from narrative are done by putting them into Shock.  We have a 20gb reads file that we used for testing, and I know that a bunch of people have uploaded that file a few times.  I do not think those uploads have a handle or workspace reference associated with them, so those are definitely dangling.  It's probably not an urgent issue, but it would free up a fair amount of space.

There are also a boatload of old workspace objects that we loaded quite a while ago for search.  I don't think that's a lot of disk space but it's probably a large number of Shock nodes (and therefore on-disk inodes).  GCing those would delete a lot of inodes, which might make rsyncing the Shock store slightly easier.

**Pull request merged**
