### PR TITLE
Adding Homology Search Product Description 2.0

### PR DESCRIPTION
**Pull request by cshenry**
Adding Homology Search Product Description 2.0

### CODE REVIEW

**Comment by scanon** [comment]
@cshenry   Can we re-scope this based on the Hyde Park meeting?  I think we were looking at two sprints.  Also, remove any references to team leads since the PD should just be about the product.

**Comment by cshenry** [comment]
Maulik - please review my latest commit carefully, and feel free to edit it. I trimmed out content that was covered by our previous work and focused exclusively on new content we're proposing. You'll see I added a 'reannoation tool', which I view as critical to creating an ecology. But I'm concerned that this isn't 2 sprints of work. Maybe we could mark the tree tool as optional too? Or the re-annotation tool? I'd like to know what others think about priorities here.

**Comment by aparkin** [comment]
Hi all, 

One of the critical pieces of this is the representation of genes and their sets in the system. Just getting this right alone is worthy of a product description. First, ideally, sequences should not HAVE to be associated with a genome or one genome in any case... or might come from genomes not in the system (e.g. GFP). "Gene" is an overloaded word and we should consider it carefully. There is open-reading frame, there is spliced exonic part of an "ORF", there is a protein sequence, RNA sequence, etc. A sequence set might be constructed in multiple ways and it should be possible to determine how it was constructed. On system- provenance should help-- if uploaded the metadata should help. it would be good to have a design for handling these biological sequence types in the system period.

**Comment by cshenry** [comment]
Adam - absolutely agreed on all of this. I see the hashing out of this design as an implementation detail that should and will absolutely appear in the implementation plan. I think the nice thing here is we can proceed with making the implementation now, and immediately begin discussions with Matt H. and other stakeholders to make sure we get the spec right. But again, I completely agree with all the principles you've laid out here. When I thought about this PD and why we opted not to deploy our homology tools in narrative, I just kept coming back to this problem of how features are represented in narrative... well, it seems we should try and solve this.

**Pull request merged**
