### PR TITLE
update with post GWAS and phytozome

### PR DESCRIPTION
**Pull request by pranjan77**

### CODE REVIEW

**Comment by aparkin** [comment]
@pranjan77 Do you really thinking getting GFF working in upload (and download) and getting all the plants from Phytozome and QA/QC will take one sprint?

**Comment by pranjan77** [comment]
@aparkin It should take less than that. It is a conservative estimate depending upon the team that implements it and their familiarity with transform service.

**Comment by mlhenderson** [comment]
I think this is underestimating the actual work involved. Anything that
touches this has to be tested with many different input data, including
viewers/visualizers, landing pages, any narrative/SDK methods that
connect.  There is also documentation and the upload UI.

**Comment by pranjan77** [comment]
As with Genbank file formats, there are some variations in the way things are coded in GFF format. So some work will be involved in identifying the different sources of GFF formatted file. It will be very difficult to write a single parser that takes care of all possible situations. So we may have to take the gff source as one of the inputs to the uploader and have a backend parser for each source. It will make the problem tractable. 

Also, GFF output from any genome annotation tool only has structural annotation information. So some time will go towards identifying the right format for capturing functional annotation and aliases. 

Once we have the gff parsers, fasta file and acceptable functional annotation file format in place, we will need parsers to convert these to Genbank format. We already have loaders and validators for Genbank file format so we can reuse the already existing loaders/viewers/visualizers, landing pages etc.

**Comment by aparkin** [comment]
My point is this is a lot harder than it seems and it is unlikely to take one sprint to design, implement, test and document the uploader/downloader and also to load all the data, no?

**Comment by aparkin** [comment]
Just as @mlhenderson pointed out above.

**Comment by pranjan77** [comment]
I would go with whatever @mlhenderson decided is the right number of sprints for this.

**Comment by nlharris** [comment]
> My point is this is a lot harder than it seems and it is unlikely to take one sprint to design, implement, test and document the uploader/downloader and also to load all the data, no?

This is confusingly worded--it sounds like Adam means it would take LESS than one sprint (which I think is how Ranjan originally interpreted Adam's question), but he is saying he thinks it will take MORE than one sprint to do a good job on this task.

**Comment by aparkin** [comment]
Yes

**Pull request merged**
