### PR TITLE
Automated developer documentation improvements

### PR DESCRIPTION
**Pull request by MrCreosote**

### CODE REVIEW

**Comment by MrCreosote** [comment]
No comments for a week, so I'll merge tomorrow unless something comes up.

**Comment by dangunter** [comment]
This looks pretty good for reference documentation. But I wonder if we can also include some way to show examples. They are usually very helpful for learning an interface. Not a show-stopper if not, just wanted to bring up the issue.

**Comment by MrCreosote** [comment]
There's nothing preventing anyone from putting examples into the spec file, and said examples would then be propagated to all the generated documentation. Are you thinking of something more than that, e.g. some way of marking the examples so they're prettified?

**Comment by dangunter** [comment]
Well, it is merged, but obviously (to me) all language examples are slightly different and therefore can't be put in a spec-file without a per-language conditional branch or some other mechanism.

**Comment by MrCreosote** [comment]
Oh yeah, duh. How do other multi language code/documentation generators handle this?

**Pull request merged**
