### PR TITLE
[WIP] Data to file product description

### PR DESCRIPTION
**Pull request by psdehal**

### CODE REVIEW

**Comment by mlhenderson** [comment]
"The reads types defined in both the KBaseAssembly and KBaseFile namespaces.  
 +\* How to pull objects from the KBase Workspace. 
 +\* The nested relationships defined by the types.
 +\* The KBase Handle service.
 +\* The KBase Shock service.
 +\* How to pull files from the KBase SHOCK data store.
 +\* How to authenticate independently across the multiple data services involved.
 +\* Indirect indication that paired ends reads are interleaved.
 +\* Indirect indication that reads are compressed.
 +\* Most importantly, the user has to understand all the possible error states of the Workspace, Handle and SHOCK services."

The non-Reads specific items are addressed by the KBase Data API for Genome types.  We don't yet have a generic way to deal with Handle and Shock (a Blob API), but we do have a generic API for pulling workspace objects (Object API), and for the Genome types we completely hide access to Handle and Shock, so you only have one interface, one way/place to authenticate.

The Reads specific items could be resolved with a Reads API for Data API, and probably updating the types to resolve the issues you point out.

I think SDK developers would want to use the KBase Data API because of the complaints that you listed for accessing data in KBase.  If it is not already possible to use the Data API from the SDK, we should fix that, because it would resolve a lot of these issues.

**Comment by dangunter** [comment]
So, an idea on how to do this somewhat generically without completely circumventing and ignoring the Data API. We could extend the base interface with a couple of methods, e.g., "export_file(<type>, {<params>})" and "get_file_types()", and this interface would be implemented in all subclasses such as the current ones or a new "Reads API". This would make it easy for people to generate a file, if the conversion type/code exists. Easily adding a new converter would depend on improving ease of use of the Data API in general, which means it wouldn't get done in this campaign; but otoh that is something that should be on our roadmap anyways (unless we ditch the Data API completely).

**Comment by mlhenderson** [comment]
How this gets implemented in the system is important to avoid duplication of effort or at least make sure that this work can be incorporated well into the system over the long term.  Whomever is tasked with implementing this, I would like to be involved in the design conversations because I have some thoughts on how we could do this now and how we could incorporate this in the long term.

**Comment by aparkin** [comment]
It is exceptionally important that Matt be consulted on this.

**Pull request merged**
