### PR TITLE
Add Bulk Download PD

### PR DESCRIPTION
**Pull request by danielolson5**

### CODE REVIEW

**Comment by aparkin** [comment]
While I appreciate the need for this, I would like to see more users requesting download of analyses from the system rather than our reference data. That they can get from other resources. I know we want to provide this functionality soon. BUt I can see putting this off a quarter or two until we see the uptick in people doing bulk analysis given everything else we have to accomplish. I am still also concerned about bulk upload being refined and our reference data cycle being optimized and expanded to other data types.

**Comment by cshenry** [comment]
We have had a number of users construct over 100 models and run large numbers of FBA analysis... and with Bills tool for running narrative operations in loops, this is going to increase... massively.

We are going to increasingly have users with large amounts of data "locked" in the system. I think some sort of bulk download scheme is going to be needed on the short term... I agree that ref data should not be the focus. I think maybe we might be able to reduce the scope of this and focus specifically on offering 1 simple mechanism that enables users to pull alot of data quickly out of a narrative...

**Comment by aparkin** [comment]
Ok. Let's see how that goes. I am just looking at the large number of PDs and trying to figure how to sequence them properly. The true bulk execution methods are only being proposed this next quarter. When they are complete I can definitely see investing in bulk download as well. If we do it right we will have more than one set of methods to bulk execute as well thereby justifying the more general solution. I get it that the bulk execution is decreased in value without download.. but it is even less value if there are not good tools for getting the large sets of data into the system, well organized and annotated by users, and if there aren't at least a couple of high value bulk execution pipelines. Modeling is certainly one of these. As Dan suggests, RNA-SEQ is the other perhaps. Or at least the tuxedo suite.

**Comment by cshenry** [comment]
I agree. The HPC PDs, which need some fleshing and differentiating, I think will end up taking priority... those could have a huge impact... particularly on RNA-seq.

**Comment by aparkin** [comment]
Yes. I hope we can get to HPC too. It seems really important. I am ignorant enough here not to see the whole can of worms involved but it could change our landscape.

**Pull request merged**
