### PR TITLE
Narrative Race Condition / Simultaneous Editing Product Proposal

### PR DESCRIPTION
**Pull request by msneddon**

### CODE REVIEW

**Comment by scanon** [comment]
This looks pretty good to me.

**Comment by dangunter** [comment]
I think merging is too hard; I would need a lot of convincing to trust it farther than I could throw it. I would defer this to a separate sprint. I would rather see better UI support for token-passing, including passing the token to "nobody" i.e. changing to read-only mode.

**Comment by msneddon** [comment]
@dangunter I'm not sure what you mean by token passing. I assume you aren't referring to the authentication token?  Do you mean passing a "lock" around?

Regarding a narrative merge, I know "merging" always sounds too complicated, but I'm actually fairly confident that merging at the narrative cell level (not within a cell) would be straightforward and should be doable by several people in that first sprint.  Each narrative cell has a unique ID in the data, so cells would be easy to match up.  If a cell is modified in one version, but not the other, we take the modifications.  If they are modified in both in any way, we duplicate the cell with a new ID and put in a markdown cell with a red begin/end conflict or something like that.  The only case I'm not exactly sure how to handle is if the ordering of cells changes in both versions in different ways.  A simple option might be to arbitrarily select one ordering and indicate in markdown cells what happened.  Or maybe we can see what git does and do something similar.

But maybe I'm missing some other issue with merging in this context.  Maybe @briehl can comment on feasibility?

I think the problem here is we can't just say "You cannot save because the narrative has been modified by another user" (which is the quick race condition fix) and give no option other than force the user to lose their work.  That's probably worse than what we have now which will at least keep the history of all changes.  Forking the Narrative completely on any non-sync change doesn't seem great, because there is no way to compare Narratives after and most of the time the change will be in adding or running a single app (which forces a save anyway).  Explicit locks would do the trick, but actually seems like much more work to me to get working in a way that makes sense.  We would need to figure out how locks get passed around, who is allowed to change them and when, how locks are stored on the back end, and we would still have the race condition issue unless we enforced that a narrative always is locked by a single user and we show read-only access to everyone else.

**Comment by dangunter** [comment]
Yes, I mean token-passing as in passing around the edit token. So what I am basically suggesting is the older style of version control where only one person at a time could actually be an editor, e.g. what you see in RCS. I assume locks would be stored the same place the information about who is editing a given document is stored, which your design also requires.

And in my experience editing code cells, moving cells around and splitting/merging cells is common. So merges will be non-trivial. And since the unique IDs are not visible to the user, non-transparent as well.

Another reason I am suggesting more limited scope is that I think the general solution is best done inside Jupyter itself and not by us. There has been nothing mentioned that I see as KBase-specific about concurrent editing, except the fact that the data is stored in MongoDB instead of the filesystem (but this can be abstracted).

**Comment by nlharris** [comment]
See discussion in https://atlassian.kbase.us/browse/KBASE-2891.
It would be great to really fix this issue, but if there's not time for that, then a warning popup would be a lot better than nothing.

**Pull request merged**
