### PR TITLE
Support NaN and Infinity in KBase

### PR DESCRIPTION
**Pull request by MrCreosote**

### CODE REVIEW

**Comment by scanon** [comment]
@MrCreosote  Can we add a specific example of where this is an issue?  I think that would be helpful.

**Comment by MrCreosote** [comment]
I personally ran into this problem way back when I was working on the experimental stuff. BarSeq and TnSeq can have NaNs in the data set, IIRC. I remember @realmarcin had the same issue with some of his data as well, but I don't remember the context.

**Comment by realmarcin** [comment]
I assume this is regarding type specs? Or is it content in json objects? Perhaps both ...

In any case, this comes up in gene expression data which we handle in FeatureValue and RNAseq as NaN values correspond to no measurement for a gene in a given sample. This is notorious when analyzing multiple samples, especially for RNAseq but also other data types. In general its a way to represent 'no measurement' in biological data.

As for Infinitity, that can come up in tree distances, taking logs, p-value=0 -- but no immediate kbase bio examples I can think of (perhaps in the output of Sequence Search? perhaps the ratio creation steps in RNAseq?).

**Comment by scanon** [comment]
So can you draft up one concrete example to include in the user story section?

**Comment by realmarcin** [comment]
Sure, though I can't edit on this branch:

A user would like to upload and use a collection of RNAseq gene expression ratios as a FeatureValue matrix. Some of the genes were never observed in only certain samples, hence when creating comparisons between treatment and control samples those sample values and sample-to-sample ratios need to allow an NaN value corresponding to 'gene was not measured'. This is to distinguish from 0 values which would correspond to a actual measurement, would be included in normalization etc.

**Comment by scanon** [comment]
Great.  Gavin: Can you add this and then I can go ahead and merge it.

**Comment by MrCreosote** [comment]
@scanon done

**Pull request merged**
