### PR TITLE
[WIP] Unified Data Sharing PD

### PR DESCRIPTION
**Pull request by mlhenderson**

### CODE REVIEW

**Comment by MrCreosote** [comment]
Sorry if I'm being dense, but it seems to me that everything except

> As a KBase developer, I want to make reference data publicly readable by KBase users, but distinct from public data shared by regular KBase users.

... is already implemented in the Narrative. Am I missing something?

**Comment by aparkin** [comment]
I think @MrCreosote has a point in terms of PD. I think I know what you are trying to fix Matt but it is not clear from your PD what is not working and what demands fixing now.

**Comment by mlhenderson** [comment]
Here is the directive from Adam's document on high priority items that this
was targeted for.  I left out implementation details based on the
understanding that those should not appear in a product description.

"Fix sharing. Sharing is a key concept in KBase and something we talk a lot
about as a differentiator. However, it is still cumbersome and difficult to
understand. There are several related tasks here that would greatly improve
our sharing experience. Extend user profile to support very simple groups.
Allow narratives to be shared by email address. Filter shared narratives by
user(s). Fix data sharing so that it does what people think it does."

**Comment by aparkin** [comment]
Right-- but there are a series of accessor methods, visualization, data browser proposals, group definition products, etc. that could impact all this. So there is a question of what the dependencies and scope is. Does this require a whole new design; complete rewiring of sharing; or a set of methods that allows us to dice and slice our shared data and display data selectors based on this. Would a lot be helped by really nice ways to find and group collaborators so you could more easi;y share to the group, etc. 

I don't really know...just asking.

**Comment by mlhenderson** [comment]
I guess the way I was interpreting these PDs based on the constraints (no implementation proposed) that really these are problems that should be tackled or new features added, and they are either selected as important and scheduled, either immediately or at some point in the future, or deselected as not important.

How the task realistically gets accomplished will have to be determined on the ground by the implementers, at least based on my understanding of how this should work.  

For this particular PD, in the first sprint stakeholders (ideally users) would provide feedback to determine what the scope of the work should be.  I did not specifically mention groups for example, although that may in fact be one of the high priority items to deal with as indicated by the stakeholders.

If this PD is considered too vague, I might need some guidance on what is actually expected that would not include implementation details.  I'm happy to make revisions as needed.

**Comment by aparkin** [comment]
I am not criticizing the level of detail particularly. I am saying that it overlaps in part with other products being proposed. Yes- these products to be tackling problems and adding features. And we are RIGHT NOW going through the prioritization and selection or rescheduling. 

For this particular case we might want to think about the following: 

1) We have a current sharing model. It is working kinda. There are some specific defects we need to address. What are they?
2) We have a proposal in another PD to institute a group management piece. How would this impact any model of sharing. This PD is in response both to internal thought and user feedback. So the question is does that PD owner think we have appropriate feedback to make this part of things. If so this might impact how you drive a proposed user study on sharing. It may be you want the entire PD to be deliver of a sharing model based on feedback. But the idea is you would design that in part based on knowledge of current limitations of sharing and in some of the related ambitions (such as groups).

**Comment by aparkin** [comment]
Part of my point here is that there are some complexities that users will not appreciate until they really start working with the system. I'll consider a specific use case here. 

I am running a large project called X with ten collaborating labs each of which has between 1 and 5 personnel in addition to the PI. We have point collaborations outside the project with people who help us, but those investigators have different privacy issues than within project. For example, all investigators within the project have agreed to share unpublished data freely. But our outside collaborator has not made such an agreement so data coming from their lab might only be shared with me (or another project X investigator). 

My lab is involved in high throughput RNA-SEQ of plants and I am planning on creating a collection of data sets of the type (Condition X, Individual plant N, (Tissue M, RNA-Data)) implying I am measuring expression response of a species of plant over X conditions. In each condition, I am measuring gene expression in M different tissues according to some attached protocol. My collection is the set of data sets over X. 

I want to be able to upload into KBase the reads in bulk from these experiments and share them with the project, and with these outside investigators. I might want to share individual subsets of these experiments (the datasets) with outside people. I'd like to make sure that permissions are not inherited by derived data products but I do want to make it easy to transfer those permissions as such. Also-- the individual datasets should likely have the same permissions as the collection, right?

Now let's say one of my outside collaborators is also doing RNA-SEQ of a similar style on a related plant. She has given me permission to perform a comparative analysis that might ultimately be shared with Project X but not yet. She shares her data with me. I create a collection containing a selected subset of datasets from my collection and from hers. Now I share this collection perhaps inadvertently with Project X. What should have happened? Well-- it could be that all the datasets in the new collection inherit the permissions from the new collection container; it could be they maintain their permissions from where I got 'em. If it is the latter then I shouldn't be able to share my new collection with Project X without a warning and a specific choice being made because datasets in the collection are really private to me and this outside investigator. (We might just say-- so what? That is the responsibility of me not to share data I promised to keep private-- but you can see how this could become confusing to a user... so giving a warning at least might be useful.) If it is the former then we have to keep track of a complex maze of permissions on references to data sets that seems hard to manage and confusing to a user. 

There are other interesting issues here as well. What if I share DERIVED data from this set with the group. Again-- we could argue this is my responsibility. And it is. But sharing a Narrative might share ALL data equally (which it probably should) or if I make a new NArrative with just the derived data and share that-- then if Project X members reach back to figure out where the data set came from with provenance-- should they be able to know that while they may not have access to the input new collection that this collection was derived from Project X data (which they DO have access to) and a private collection?

In any case, my point is that the above would be hard for users who can barely use the interface as is to imagine yet and it is in part incumbent upon us to derive a reasonable model. Further, the above implies a series of operations on collections (upload, download, controlled subsetting, etc) that need to be operational and linked to any sharing system we derive. During sharing, we have to think about permission inheritance if there is any when data in brought together and the implications of that. 

So it seems like among understanding well what we have, what we know we want to do, and what users experience to date has been we should be able to set up an example of what extensions and fixes to our sharing system should enable.

**Comment by mlhenderson** [comment]
Currently, if Narratives and data (input or output of methods) share the same container (workspace), they have the same permissions, and there is no distinction for derived products.  There is no distinction between items in the container in terms of permissions.  This may or may not fit user expectations.

It sounds like you should be a stakeholder!

What you are describing are rules/policies that users could assign.  For instance, "alert me if my Narrative or data is shared with others".  My question though would be whether this generally meets user expectations, or if they expect stricter policy enforcement.  I think you are right that users have probably not encountered a complex sharing scenario yet in KBase.  Simulating a lab of researchers as a scenario for evaluation and testing would be a good way to identify specific problems, what the desired behavior should be, and then possible solutions.  I would be concerned about making sure we had a minimally viable product to deliver at the end of the quarter, so scoping appropriately is crucial.

**Comment by scanon** [comment]
I originally thought the purpose of this item was much more "simple" and it was just about having one service the knew how to talk to other KBase services to correctly share a workspace and all its related pieces (shock, awe, jobs, etc). So this would be able to replace NJP and handle manager and possibly some other things. There are lots of edge cases right now where we struggle to propagate the sharing correctly. This thing would be the uber sharer.

**Comment by aparkin** [comment]
What you suggest Shane would be a great step in the right direction

**Comment by dangunter** [comment]
So, what is the difference between adding a new sharing broker, and adding more metadata to the workspace object, which is the granularity of sharing in the system, to manipulate associated identifiers?

**Pull request merged**
